-- Data Engineering interview level while keeping your exact format.

-- These will now test:

-- join cardinality awareness

-- WHERE vs HAVING

-- NULL traps

-- aggregation correctness

-- real business metrics

-- anti-join patterns

-- execution order thinking

-- ============================================================
-- Question 1 — Daily Paying Users
-- ============================================================
-- Table: orders
-- | order_id | user_id | order_time  | amount |
-- |----------|---------|-------------|--------|
-- | 1        | 101     | 2026-03-10  | 200    |
-- | 2        | 102     | 2026-03-10  | 0      |
-- | 3        | 101     | 2026-03-10  | 100    |
-- | 4        | 103     | 2026-03-11  | 300    |
-- | 5        | 104     | 2026-03-11  | 0      |
--
-- Business Problem
-- Finance wants to measure the number of **paying users per day**.
-- A paying user is someone whose order amount is greater than 0.
--
-- Return:
-- | order_date | paying_users |
-- ============================================================

-- Write your query below:
--
SELECT order_time AS order_date,
       COUNT(DISTINCT user_id) AS paying_users
FROM orders
WHERE amount > 0
GROUP BY order_time;
--



-- ============================================================
-- Question 2 — Countries Generating Revenue
-- ============================================================
-- Table: users
-- | user_id | country |
-- |---------|---------|
-- | 101     | India   |
-- | 102     | USA     |
-- | 103     | India   |
-- | 104     | Canada  |
-- | 105     | USA     |
--
-- Table: orders
-- | order_id | user_id | amount |
-- |----------|---------|--------|
-- | 1        | 101     | 200    |
-- | 2        | 101     | 150    |
-- | 3        | 102     | 50     |
-- | 4        | 103     | 300    |
-- | 5        | 104     | 250    |
--
-- Business Problem
-- The analytics team wants total revenue generated by each country.
--
-- Return:
-- | country | total_revenue |
-- ============================================================

-- Write your query below:
--
SELECT u.country,
       SUM(o.amount) AS total_revenue
FROM users u 
INNER JOIN orders o ON o.user_id = u.user_id
GROUP BY u.country;
--



-- ============================================================
-- Question 3 — Users Who Never Ordered
-- ============================================================
-- Table: users
-- | user_id | name  |
-- |---------|-------|
-- | 101     | Rahul |
-- | 102     | Neha  |
-- | 103     | Arjun |
-- | 104     | Priya |
-- | 105     | Aman  |
--
-- Table: orders
-- | order_id | user_id | amount |
-- |----------|---------|--------|
-- | 1        | 101     | 200    |
-- | 2        | 103     | 300    |
-- | 3        | 101     | 100    |
--
-- Business Problem
-- Marketing wants to identify users who have **never placed an order**.
--
-- Return:
-- | user_id | name |
-- ============================================================

-- Write your query below:
--
SELECT DISTINCT(u.user_id),
                u.name
FROM users u 
LEFT JOIN orders o 
         ON o.user_id = u.user_id
WHERE o.user_id IS NULL;
--



-- ============================================================
-- Question 4 — High Value Revenue Report
-- ============================================================
-- Table: orders
-- | order_id | user_id | order_time | amount |
-- |----------|---------|------------|--------|
-- | 1        | 101     | 2026-03-10 | 200    |
-- | 2        | 102     | 2026-03-10 | 50     |
-- | 3        | 103     | 2026-03-10 | 500    |
-- | 4        | 104     | 2026-03-11 | 600    |
-- | 5        | 105     | 2026-03-11 | 80     |
--
-- Business Problem
-- Finance wants to know daily revenue from high-value orders (>100).
--
-- Return:
-- | date | high_value_revenue |
-- ============================================================

-- Write your query below:
--
SELECT order_time AS date,
       SUM(amount) AS high_value_revenue
FROM orders
WHERE amount > 100
GROUP BY order_time;
--



-- ============================================================
-- Question 5 — Countries With Large Revenue
-- ============================================================
-- Table: users
-- | user_id | country |
-- |---------|---------|
-- | 101     | India   |
-- | 102     | USA     |
-- | 103     | India   |
-- | 104     | Canada  |
-- | 105     | USA     |
--
-- Table: orders
-- | order_id | user_id | amount |
-- |----------|---------|--------|
-- | 1        | 101     | 200    |
-- | 2        | 101     | 150    |
-- | 3        | 102     | 50     |
-- | 4        | 103     | 300    |
-- | 5        | 104     | 250    |
-- | 6        | 105     | 30     |
--
-- Business Problem
-- The finance team wants countries where total revenue exceeds 400.
--
-- Return:
-- | country | total_revenue |
-- ============================================================

-- Write your query below:
--
SELECT u.country,
       SUM(o.amount) AS total_revenue
FROM users u 
LEFT JOIN orders o 
         ON o.user_id = u.user_id;
GROUP BY u.country
HAVING  SUM(o.amount) > 400
--



-- ============================================================
-- Question 6 — Users With Multiple Orders
-- ============================================================
-- Table: orders
-- | order_id | user_id | amount |
-- |----------|---------|--------|
-- | 1        | 101     | 200    |
-- | 2        | 101     | 150    |
-- | 3        | 102     | 300    |
-- | 4        | 103     | 250    |
-- | 5        | 103     | 100    |
-- | 6        | 103     | 50     |
--
-- Business Problem
-- Product analytics wants to find users who placed **more than 2 orders**.
--
-- Return:
-- | user_id | order_count |
-- ============================================================

-- Write your query below:
--
SELECT user_id,
       COUNT(*) AS order_count
FROM orders 
GROUP BY user_id
HAVING COUNT(*) > 2;
--



-- ============================================================
-- Question 7 — Orders Without Matching Users
-- ============================================================
-- Table: users
-- | user_id | name |
-- |---------|------|
-- | 101     | Rahul|
-- | 102     | Neha |
-- | 103     | Arjun|
--
-- Table: orders
-- | order_id | user_id | amount |
-- |----------|---------|--------|
-- | 1        | 101     | 200    |
-- | 2        | 102     | 150    |
-- | 3        | 105     | 300    |
--
-- Business Problem
-- Data quality team wants to identify orders that reference users
-- that do not exist in the users table.
--
-- Return:
-- | order_id | user_id |
-- ============================================================

-- Write your query below:
--
SELECT o.order_id,o.user_id
FROM users u 
RIGHT JOIN orders o 
          ON o.user_id = u.user_id
WHERE u.user_id IS NULL;
--



-- ============================================================
-- Question 8 — Top Revenue Users
-- ============================================================
-- Table: orders
-- | order_id | user_id | amount |
-- |----------|---------|--------|
-- | 1        | 101     | 200    |
-- | 2        | 101     | 150    |
-- | 3        | 102     | 300    |
-- | 4        | 103     | 250    |
-- | 5        | 103     | 100    |
--
-- Business Problem
-- Finance wants the **top 2 users by total revenue generated**.
--
-- Return:
-- | user_id | total_revenue |
-- ============================================================

-- Write your query below:
--
SELECT user_id,
       SUM(amount) AS total_revenue
FROM Orders
GROUP BY user_id 
ORDER BY SUM(amount) DESC
LIMIT 2;
--


-- ============================================================
-- Question 10 — Referral Network (Self Join)
-- ============================================================
-- Table: users
-- | user_id | name   | referred_by |
-- |---------|--------|-------------|
-- | 101     | Rahul  | NULL        |
-- | 102     | Neha   | 101         |
-- | 103     | Arjun  | 101         |
-- | 104     | Priya  | 102         |
-- | 105     | Aman   | NULL        |
--
-- Business Problem
-- Product wants to analyze the referral network and see which
-- users successfully referred others.
--
-- Return:
-- | referrer_name | referred_user |
-- ============================================================

-- Write your query below:
--

--